const PRAYERS=[
  {key:'fajr',name:'Fajr',bn:'ফজর',icon:'🌄'},
  {key:'dhuhr',name:'Dhuhr',bn:'যোহর',icon:'☀️'},
  {key:'asr',name:'Asr',bn:'আসর',icon:'🌤️'},
  {key:'maghrib',name:'Maghrib',bn:'মাগরিব',icon:'🌇'},
  {key:'isha',name:'Isha',bn:'এশা',icon:'🌙'}
];
const METHODS={karachi:{fajr:18,isha:18,label:'Karachi'},mwl:{fajr:18,isha:17,label:'MWL'},egypt:{fajr:19.5,isha:17.5,label:'Egypt'},isna:{fajr:15,isha:15,label:'ISNA'}};
let settings=JSON.parse(localStorage.getItem('no_settings')||'null')||{calcMethod:'karachi',asrMethod:'hanafi',adjust:0,alarmSound:'alarm',preReminder:10};
let coords=JSON.parse(localStorage.getItem('no_coords')||'null')||null;
let locationLabel=localStorage.getItem('no_location_label')||'Saved / fallback location';
let todayTimes=null;
let calCursor=new Date();
let selectedDateKey='';

const SURAH_FALLBACK=[
[1,'Al-Faatiha','الفاتحة'],[2,'Al-Baqara','البقرة'],[3,'Aal-i-Imraan','آل عمران'],[4,'An-Nisaa','النساء'],[5,'Al-Maaida','المائدة'],[6,'Al-An\'aam','الأنعام'],[7,'Al-A\'raaf','الأعراف'],[8,'Al-Anfaal','الأنفال'],[9,'At-Tawba','التوبة'],[10,'Yunus','يونس'],[11,'Hud','هود'],[12,'Yusuf','يوسف'],[13,'Ar-Ra\'d','الرعد'],[14,'Ibrahim','ابراهيم'],[15,'Al-Hijr','الحجر'],[16,'An-Nahl','النحل'],[17,'Al-Israa','الإسراء'],[18,'Al-Kahf','الكهف'],[19,'Maryam','مريم'],[20,'Taa-Haa','طه'],[21,'Al-Anbiyaa','الأنبياء'],[22,'Al-Hajj','الحج'],[23,'Al-Muminoon','المؤمنون'],[24,'An-Noor','النور'],[25,'Al-Furqaan','الفرقان'],[26,'Ash-Shu\'araa','الشعراء'],[27,'An-Naml','النمل'],[28,'Al-Qasas','القصص'],[29,'Al-Ankaboot','العنكبوت'],[30,'Ar-Room','الروم'],[31,'Luqman','لقمان'],[32,'As-Sajda','السجدة'],[33,'Al-Ahzaab','الأحزاب'],[34,'Saba','سبإ'],[35,'Faatir','فاطر'],[36,'Yaseen','يس'],[37,'As-Saaffaat','الصافات'],[38,'Saad','ص'],[39,'Az-Zumar','الزمر'],[40,'Ghafir','غافر'],[41,'Fussilat','فصلت'],[42,'Ash-Shura','الشورى'],[43,'Az-Zukhruf','الزخرف'],[44,'Ad-Dukhaan','الدخان'],[45,'Al-Jaathiya','الجاثية'],[46,'Al-Ahqaf','الأحقاف'],[47,'Muhammad','محمد'],[48,'Al-Fath','الفتح'],[49,'Al-Hujuraat','الحجرات'],[50,'Qaaf','ق'],[51,'Adh-Dhaariyat','الذاريات'],[52,'At-Tur','الطور'],[53,'An-Najm','النجم'],[54,'Al-Qamar','القمر'],[55,'Ar-Rahmaan','الرحمن'],[56,'Al-Waaqia','الواقعة'],[57,'Al-Hadid','الحديد'],[58,'Al-Mujaadila','المجادلة'],[59,'Al-Hashr','الحشر'],[60,'Al-Mumtahana','الممتحنة'],[61,'As-Saff','الصف'],[62,'Al-Jumu\'a','الجمعة'],[63,'Al-Munaafiqoon','المنافقون'],[64,'At-Taghaabun','التغابن'],[65,'At-Talaaq','الطلاق'],[66,'At-Tahrim','التحريم'],[67,'Al-Mulk','الملك'],[68,'Al-Qalam','القلم'],[69,'Al-Haaqqa','الحاقة'],[70,'Al-Ma\'aarij','المعارج'],[71,'Nooh','نوح'],[72,'Al-Jinn','الجن'],[73,'Al-Muzzammil','المزمل'],[74,'Al-Muddaththir','المدثر'],[75,'Al-Qiyaama','القيامة'],[76,'Al-Insaan','الانسان'],[77,'Al-Mursalaat','المرسلات'],[78,'An-Naba','النبإ'],[79,'An-Naazi\'aat','النازعات'],[80,'Abasa','عبس'],[81,'At-Takwir','التكوير'],[82,'Al-Infitaar','الإنفطار'],[83,'Al-Mutaffifin','المطففين'],[84,'Al-Inshiqaaq','الإنشقاق'],[85,'Al-Burooj','البروج'],[86,'At-Taariq','الطارق'],[87,'Al-A\'laa','الأعلى'],[88,'Al-Ghaashiya','الغاشية'],[89,'Al-Fajr','الفجر'],[90,'Al-Balad','البلد'],[91,'Ash-Shams','الشمس'],[92,'Al-Lail','الليل'],[93,'Ad-Dhuhaa','الضحى'],[94,'Ash-Sharh','الشرح'],[95,'At-Tin','التين'],[96,'Al-Alaq','العلق'],[97,'Al-Qadr','القدر'],[98,'Al-Bayyina','البينة'],[99,'Az-Zalzala','الزلزلة'],[100,'Al-Aadiyaat','العاديات'],[101,'Al-Qaari\'a','القارعة'],[102,'At-Takaathur','التكاثر'],[103,'Al-Asr','العصر'],[104,'Al-Humaza','الهمزة'],[105,'Al-Fil','الفيل'],[106,'Quraish','قريش'],[107,'Al-Maa\'un','الماعون'],[108,'Al-Kawthar','الكوثر'],[109,'Al-Kaafiroon','الكافرون'],[110,'An-Nasr','النصر'],[111,'Al-Masad','المسد'],[112,'Al-Ikhlaas','الإخلاص'],[113,'Al-Falaq','الفلق'],[114,'An-Naas','الناس']
];
let surahs=SURAH_FALLBACK.map(x=>({number:x[0],englishName:x[1],name:x[2]}));

function toast(msg){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove('show'),2600)}
function pad(n){return String(n).padStart(2,'0')}
function dateKey(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function localDateFromKey(k){const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d,12,0,0)}
function formatTime(d){if(!d)return '—';return d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function stateKey(k){return 'no_day_'+k}
function getDayState(k){return JSON.parse(localStorage.getItem(stateKey(k))||'null')||{}}
function setDayState(k,s){localStorage.setItem(stateKey(k),JSON.stringify(s))}
function getSchedule(k){return JSON.parse(localStorage.getItem('no_schedule_'+k)||'null')}
function saveSchedule(k,times){const out={};for(const p of PRAYERS){out[p.key]=times[p.key].getTime()}out.sunrise=times.sunrise.getTime();localStorage.setItem('no_schedule_'+k,JSON.stringify(out))}

function dtr(d){return d*Math.PI/180} function rtd(r){return r*180/Math.PI} function fixAngle(a){return ((a%360)+360)%360} function fixHour(a){return ((a%24)+24)%24}
function julian(y,m,d){if(m<=2){y-=1;m+=12}const A=Math.floor(y/100),B=2-A+Math.floor(A/4);return Math.floor(365.25*(y+4716))+Math.floor(30.6001*(m+1))+d+B-1524.5}
function sunPosition(jd){const D=jd-2451545.0,g=fixAngle(357.529+0.98560028*D),q=fixAngle(280.459+0.98564736*D),L=fixAngle(q+1.915*Math.sin(dtr(g))+0.020*Math.sin(dtr(2*g)));const e=23.439-0.00000036*D;let RA=rtd(Math.atan2(Math.cos(dtr(e))*Math.sin(dtr(L)),Math.cos(dtr(L))))/15;RA=fixHour(RA);const decl=rtd(Math.asin(Math.sin(dtr(e))*Math.sin(dtr(L))));const eqt=q/15-RA;return{decl,eqt}}
function midDay(jd,t){const eq=sunPosition(jd+t).eqt;return fixHour(12-eq)}
function sunAngleTime(jd,angle,t,dir,lat){const decl=sunPosition(jd+t).decl,noon=midDay(jd,t);const num=-Math.sin(dtr(angle))-Math.sin(dtr(decl))*Math.sin(dtr(lat));const den=Math.cos(dtr(decl))*Math.cos(dtr(lat));let x=num/den;x=Math.max(-1,Math.min(1,x));const delta=rtd(Math.acos(x))/15;return noon+(dir==='ccw'?-delta:delta)}
function asrTime(jd,factor,t,lat){const decl=sunPosition(jd+t).decl;const angle=-rtd(Math.atan(1/(factor+Math.tan(Math.abs(dtr(lat-decl))))));const noon=midDay(jd,t);const num=-Math.sin(dtr(angle))-Math.sin(dtr(decl))*Math.sin(dtr(lat));const den=Math.cos(dtr(decl))*Math.cos(dtr(lat));let x=num/den;x=Math.max(-1,Math.min(1,x));return noon+rtd(Math.acos(x))/15}
function computeHours(date,lat,lon){const y=date.getFullYear(),m=date.getMonth()+1,d=date.getDate();const jd=julian(y,m,d)-lon/(15*24);let t={fajr:5,sunrise:6,dhuhr:12,asr:13,maghrib:18,isha:18};const method=METHODS[settings.calcMethod]||METHODS.karachi;for(let iter=0;iter<2;iter++){const x={};for(const k in t)x[k]=t[k]/24;t.fajr=sunAngleTime(jd,method.fajr,x.fajr,'ccw',lat);t.sunrise=sunAngleTime(jd,.833,x.sunrise,'ccw',lat);t.dhuhr=midDay(jd,x.dhuhr);t.asr=asrTime(jd,settings.asrMethod==='hanafi'?2:1,x.asr,lat);t.maghrib=sunAngleTime(jd,.833,x.maghrib,'cw',lat);t.isha=sunAngleTime(jd,method.isha,x.isha,'cw',lat)}const tz=-date.getTimezoneOffset()/60;for(const k in t)t[k]+=tz-lon/15+(Number(settings.adjust)||0)/60;return t}
function hourToDate(base,h){h=fixHour(h);const d=new Date(base.getFullYear(),base.getMonth(),base.getDate(),0,0,0,0);d.setMinutes(Math.round(h*60));return d}
function computePrayerTimes(date){const c=coords||{lat:23.8103,lon:90.4125};const h=computeHours(date,c.lat,c.lon),r={};for(const k in h)r[k]=hourToDate(date,h[k]);return r}
function endForPrayer(times,key,nextTimes){if(key==='fajr')return times.sunrise;if(key==='dhuhr')return times.asr;if(key==='asr')return times.maghrib;if(key==='maghrib')return times.isha;return nextTimes?nextTimes.fajr:new Date(times.isha.getTime()+8*3600000)}

function autoUpdateQaza(){const now=new Date();const todayK=dateKey(now);const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('no_schedule_'))keys.push(k.replace('no_schedule_',''))}if(!keys.includes(todayK))keys.push(todayK);for(const k of keys){let schedule=getSchedule(k);if(!schedule){if(k!==todayK)continue;const times=computePrayerTimes(now);saveSchedule(k,times);schedule=getSchedule(k)}const state=getDayState(k);const nextDate=new Date(localDateFromKey(k));nextDate.setDate(nextDate.getDate()+1);const next=computePrayerTimes(nextDate);for(const p of PRAYERS){if(state[p.key]==='complete'||state[p.key]==='qaza-complete')continue;const temp={};for(const q of PRAYERS)temp[q.key]=new Date(schedule[q.key]);temp.sunrise=new Date(schedule.sunrise);const end=endForPrayer(temp,p.key,next);if(now>end)state[p.key]='qaza'}setDayState(k,state)}}
function markComplete(k,p,fromQaza=false){const s=getDayState(k);s[p]=fromQaza?'qaza-complete':'complete';s[p+'_at']=Date.now();setDayState(k,s);refreshAll();toast(fromQaza?'Qaza marked complete':'Prayer marked complete')}
function markUndo(k,p){const s=getDayState(k);delete s[p];delete s[p+'_at'];setDayState(k,s);refreshAll()}

function findNextPrayer(now,times){for(const p of PRAYERS){if(times[p.key]>now)return{p,date:times[p.key]}}const tomorrow=new Date(now);tomorrow.setDate(tomorrow.getDate()+1);const tt=computePrayerTimes(tomorrow);return{p:PRAYERS[0],date:tt.fajr}}
function renderToday(){const now=new Date();const k=dateKey(now);todayTimes=computePrayerTimes(now);saveSchedule(k,todayTimes);autoUpdateQaza();const s=getDayState(k);const next=findNextPrayer(now,todayTimes);document.getElementById('nextPrayer').textContent=next.p.bn;const complete=PRAYERS.filter(p=>s[p.key]==='complete'||s[p.key]==='qaza-complete').length;const qaza=PRAYERS.filter(p=>s[p.key]==='qaza').length;document.getElementById('completeCount').textContent=complete;document.getElementById('todayPercent').textContent=Math.round(complete/5*100)+'% complete';document.getElementById('qazaBadge').textContent='Qaza '+qaza;document.getElementById('statComplete').textContent=complete;document.getElementById('statQaza').textContent=qaza;document.getElementById('locationText').textContent=locationLabel;document.getElementById('statLoc').textContent=coords?'GPS':'Dhaka';document.getElementById('methodChip').textContent=(METHODS[settings.calcMethod]||METHODS.karachi).label+' • '+(settings.asrMethod==='hanafi'?'Hanafi':'Standard');const list=document.getElementById('todayPrayerList');list.innerHTML='';for(const p of PRAYERS){const status=s[p.key]||'pending';const div=document.createElement('div');div.className='prayer-card glass';let statusText=status==='complete'?'✓ Complete':status==='qaza'?'Qaza due':status==='qaza-complete'?'✓ Qaza complete':(todayTimes[p.key]>now?'Upcoming':'In prayer window');let action='';if(status==='pending'&&todayTimes[p.key]<=now)action=`<button class="action" onclick="markComplete('${k}','${p.key}')">Prayer Complete</button>`;if(status==='complete')action=`<button class="action" onclick="markUndo('${k}','${p.key}')">Undo</button>`;if(status==='qaza')action=`<button class="action warn" onclick="markComplete('${k}','${p.key}',true)">Complete Qaza</button>`;div.innerHTML=`<div class="prayer-icon">${p.icon}</div><div><h4>${p.bn} <small>• ${p.name}</small></h4><small>Start ${formatTime(todayTimes[p.key])}</small>${action}</div><div class="time">${formatTime(todayTimes[p.key])}<div class="status ${status==='qaza'?'qaza':status.includes('complete')?'complete':''}">${statusText}</div></div>`;list.appendChild(div)}updateCountdown();scheduleAlarms()}
function updateCountdown(){if(!todayTimes)return;const now=new Date(),n=findNextPrayer(now,todayTimes),ms=Math.max(0,n.date-now),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);document.getElementById('countdown').textContent=`${pad(h)}:${pad(m)}:${pad(s)}`;document.getElementById('statNext').textContent=h?`${h}h ${m}m`:`${m}m`}

