function detectLocation(){if(!navigator.geolocation){toast('Geolocation not available');return}document.getElementById('locationText').textContent='Detecting location…';navigator.geolocation.getCurrentPosition(async p=>{coords={lat:p.coords.latitude,lon:p.coords.longitude};localStorage.setItem('no_coords',JSON.stringify(coords));locationLabel=`${coords.lat.toFixed(3)}, ${coords.lon.toFixed(3)}`;try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${coords.lat}&lon=${coords.lon}`,{headers:{'Accept':'application/json'}});if(r.ok){const j=await r.json();locationLabel=j.display_name||locationLabel}}catch(e){}localStorage.setItem('no_location_label',locationLabel);renderToday();renderCalendar();toast('Location updated')},e=>{document.getElementById('locationText').textContent=locationLabel;toast('Location permission was not available. Using saved/fallback location.')},{enableHighAccuracy:true,timeout:12000,maximumAge:300000})}

function scheduleAlarms(){if(!window.AndroidBridge||!todayTimes)return;const sound=settings.alarmSound||'alarm',pre=Number(settings.preReminder)||0;try{window.AndroidBridge.requestExactAlarmPermission()}catch(e){}for(let dayOffset=0;dayOffset<=1;dayOffset++){const d=new Date();d.setDate(d.getDate()+dayOffset);const times=computePrayerTimes(d),k=dateKey(d);for(const p of PRAYERS){const at=times[p.key].getTime();if(at>Date.now())window.AndroidBridge.scheduleAlarm(`${k}_${p.key}`,`${p.bn} • ${p.name}`,at,sound);if(pre>0&&at-pre*60000>Date.now())window.AndroidBridge.scheduleAlarm(`${k}_${p.key}_pre`,`${p.bn} ${pre} মিনিট পরে`,at-pre*60000,sound)}}}
function requestExactAlarm(){if(window.AndroidBridge){window.AndroidBridge.requestExactAlarmPermission();toast('Exact alarm settings opened if required')}else toast('Exact alarm control is available in Android APK')}

function shiftMonth(n){calCursor=new Date(calCursor.getFullYear(),calCursor.getMonth()+n,1);renderCalendar()}
function renderCalendar(){const y=calCursor.getFullYear(),m=calCursor.getMonth();document.getElementById('calTitle').textContent=new Date(y,m,1).toLocaleDateString('bn-BD',{month:'long',year:'numeric'});const c=document.getElementById('calendar');c.innerHTML='';['রবি','সোম','মঙ্গল','বুধ','বৃহ','শুক্র','শনি'].forEach(x=>{const d=document.createElement('div');d.className='dow';d.textContent=x;c.appendChild(d)});const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++){const e=document.createElement('button');e.className='day empty';e.disabled=true;c.appendChild(e)}for(let day=1;day<=days;day++){const d=new Date(y,m,day,12);const k=dateKey(d),s=getDayState(k);const btn=document.createElement('button');btn.className='day '+(k===dateKey(new Date())?'today':'');let dots='';for(const p of PRAYERS){const st=s[p.key];dots+=`<span class="dot ${st==='qaza'?'bad':(st==='complete'||st==='qaza-complete')?'ok':''}"></span>`}btn.innerHTML=`<b>${day}</b><span class="dots">${dots}</span>`;btn.onclick=()=>selectCalendarDay(k);c.appendChild(btn)}if(!selectedDateKey)selectedDateKey=dateKey(new Date());selectCalendarDay(selectedDateKey,false)}
function selectCalendarDay(k,rerender=true){selectedDateKey=k;const d=localDateFromKey(k);document.getElementById('selectedDateTitle').textContent=d.toLocaleDateString('bn-BD',{weekday:'long',day:'numeric',month:'long',year:'numeric'});const schedule=getSchedule(k),s=getDayState(k),box=document.getElementById('selectedDayDetails');box.innerHTML='';for(const p of PRAYERS){const t=schedule?new Date(schedule[p.key]):(k===dateKey(new Date())?computePrayerTimes(d)[p.key]:null);const st=s[p.key]||'not logged';const card=document.createElement('div');card.className='prayer-card';card.innerHTML=`<div class="prayer-icon">${p.icon}</div><div><h4>${p.bn}</h4><small>${st==='qaza'?'Qaza due':st==='complete'?'Complete':st==='qaza-complete'?'Qaza complete':'Not logged'}</small></div><div class="time">${formatTime(t)}</div>`;box.appendChild(card)}if(rerender){} }

function allStoredDays(){const arr=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('no_day_'))arr.push(k.replace('no_day_',''))}return arr.sort()}
function renderQaza(){autoUpdateQaza();const box=document.getElementById('qazaList');box.innerHTML='';let due=0,done=0;for(const k of allStoredDays()){const s=getDayState(k);for(const p of PRAYERS){if(s[p.key]==='qaza'){due++;const d=document.createElement('div');d.className='qaza-item';const schedule=getSchedule(k);d.innerHTML=`<div><b>${p.bn} • ${p.name}</b><small>${localDateFromKey(k).toLocaleDateString('bn-BD')} ${schedule?'• '+formatTime(new Date(schedule[p.key])):''}</small></div><button class="btn" onclick="markComplete('${k}','${p.key}',true)">Complete</button>`;box.appendChild(d)}if(s[p.key]==='qaza-complete')done++}}document.getElementById('qazaTotal').textContent=due;document.getElementById('qazaDone').textContent=done;if(!due)box.innerHTML='<div class="panel glass"><div class="notice">কোনো Qaza due নেই।</div></div>'}

