function renderSurahList(){const q=(document.getElementById('quranSearch').value||'').toLowerCase();const box=document.getElementById('surahList');box.innerHTML='';surahs.filter(s=>(s.englishName||'').toLowerCase().includes(q)||(s.name||'').includes(q)||String(s.number)===q).forEach(s=>{const b=document.createElement('button');b.className='surah';b.innerHTML=`<b>${s.number}. ${s.englishName}</b><small>${s.name}</small>`;b.onclick=()=>openSurah(s.number);box.appendChild(b)})}
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open('namaz_orbit_quran',1);r.onupgradeneeded=()=>r.result.createObjectStore('surahs',{keyPath:'number'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbGet(n){try{const db=await dbOpen();return await new Promise((res,rej)=>{const r=db.transaction('surahs').objectStore('surahs').get(n);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}catch(e){return null}}
async function dbPut(v){try{const db=await dbOpen();await new Promise((res,rej)=>{const r=db.transaction('surahs','readwrite').objectStore('surahs').put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}catch(e){}}
async function fetchSurah(n){const cached=await dbGet(n);if(cached)return cached;const url=`https://api.alquran.cloud/v1/surah/${n}/editions/quran-uthmani,bn.bengali`;const r=await fetch(url);if(!r.ok)throw new Error('Quran API error');const j=await r.json();const arabic=j.data&&j.data[0],bangla=j.data&&j.data[1];if(!arabic||!bangla)throw new Error('Quran data unavailable');const v={number:n,name:arabic.englishName,arabicName:arabic.name,ayahs:arabic.ayahs.map((a,i)=>({number:a.numberInSurah,ar:a.text,bn:bangla.ayahs[i]?bangla.ayahs[i].text:''}))};await dbPut(v);return v}
async function openSurah(n){document.getElementById('surahBrowser').style.display='none';document.getElementById('surahReader').style.display='block';document.getElementById('surahTitle').textContent='Loading…';document.getElementById('ayahList').innerHTML='<div class="notice">Quran text loading…</div>';try{const s=await fetchSurah(n);document.getElementById('surahTitle').textContent=`${s.number}. ${s.name} • ${s.arabicName}`;document.getElementById('ayahList').innerHTML=s.ayahs.map(a=>`<article class="ayah"><div class="ayah-no">AYAH ${a.number}</div><div class="arabic">${escapeHtml(a.ar)}</div><div class="bangla">${escapeHtml(a.bn)}</div></article>`).join('')}catch(e){document.getElementById('ayahList').innerHTML='<div class="notice">Quran data could not load. Check internet and try again. Previously downloaded Surahs remain available offline.</div>'}}
function closeSurah(){document.getElementById('surahBrowser').style.display='block';document.getElementById('surahReader').style.display='none'}
function escapeHtml(s){return String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function downloadQuranOffline(){const bar=document.getElementById('quranDownloadProgress'),label=document.getElementById('quranDownloadLabel');for(let n=1;n<=114;n++){try{await fetchSurah(n)}catch(e){label.textContent=`Stopped at Surah ${n}. Check internet and tap Offline again.`;return}bar.style.width=Math.round(n/114*100)+'%';label.textContent=`Downloading Quran for offline use… ${n}/114`}label.textContent='Full Quran Arabic + বাংলা অর্থ cached for offline use.';toast('Quran offline download complete')}

