function saveSettings(){settings={calcMethod:document.getElementById('calcMethod').value,asrMethod:document.getElementById('asrMethod').value,adjust:Number(document.getElementById('timeAdjustment').value)||0,alarmSound:document.getElementById('alarmSound').value,preReminder:Number(document.getElementById('preReminder').value)||0};localStorage.setItem('no_settings',JSON.stringify(settings));renderToday();renderCalendar();toast('Settings saved & alarms rescheduled')}
function loadSettings(){document.getElementById('calcMethod').value=settings.calcMethod;document.getElementById('asrMethod').value=settings.asrMethod;document.getElementById('timeAdjustment').value=settings.adjust;document.getElementById('alarmSound').value=settings.alarmSound;document.getElementById('preReminder').value=settings.preReminder}
function exportData(){const data={settings,coords,locationLabel,history:{}};for(const k of allStoredDays())data.history[k]=getDayState(k);const text=JSON.stringify(data,null,2);if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>toast('Tracker data copied as JSON'));else toast('Clipboard unavailable')}
function resetTracker(){if(!confirm('Prayer and Qaza history delete করবেন? Settings থাকবে।'))return;const del=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&(k.startsWith('no_day_')||k.startsWith('no_schedule_')))del.push(k)}del.forEach(k=>localStorage.removeItem(k));refreshAll();toast('Tracker history reset')}

function showPage(name){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('page-'+name).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));if(name==='prayer')renderCalendar();if(name==='qaza')renderQaza();if(name==='quran')renderSurahList();if(name==='more')loadSettings();window.scrollTo({top:0,behavior:'smooth'})}
function renderDates(){const n=new Date();document.getElementById('gregorianDate').textContent=n.toLocaleDateString('bn-BD',{weekday:'long',day:'numeric',month:'long',year:'numeric'});try{document.getElementById('hijriDate').textContent=new Intl.DateTimeFormat('bn-BD-u-ca-islamic',{day:'numeric',month:'long',year:'numeric'}).format(n)}catch(e){document.getElementById('hijriDate').textContent='Hijri calendar'} }
function refreshAll(){renderDates();renderToday();renderCalendar();renderQaza()}

renderGuideGrid();renderSurahList();loadSettings();renderDates();renderToday();renderCalendar();renderQaza();
setInterval(()=>{updateCountdown();autoUpdateQaza()},1000);
setTimeout(()=>{if(!coords)detectLocation()},900);